import { Inter } from "next/font/google";
import "./globals.css";
import Search from "./Header/page";
import Sidebar from "./Sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Search />
        <div className="flex">
          <div className="mt-20">
            <Sidebar />
          </div>
          <div className="flex-1 ml-28">{children}</div>
        </div>
      </body>
    </html>
  );
}
